### ISSUE TITLE
DOC/ENH: canari.quickstart.rst

### ISSUE THREAD

**Issue by SYNchroACK** [redcanari/canari3#1]
Note: I will keep updating this issue while im reviewing...

---

**1. Linux - Fedora-based** - I think is missing python-devel package.

---

**2. Hello World!** section - I think we should have a subsection which provides an overview through all folders and files automatically created. Using the content generated to README file, I propose the following:

```
** Directory and Files Structure of the Package:**

Inside `hello` folder you can find the following files and directory structure:

* `.canari` **FIXME**
* `MANIFEST.in` **FIXME**
* `.mrbob.ini` **FIXME**
* `README` **FIXME**
* `setup.py` **FIXME**
* `src/hello` directory is where all your stuff goes in terms of auxiliary modules that you may need for your modules
* `src/hello/transforms` directory is where all your transform modules should be placed. An example `helloworld` transform is there for your viewing pleasure.
* `src/hello/transforms/helloworld.py` **FIXME**
* `src/hello/transforms/common` directory is where you can put some common code for your transforms like result parsing, entities, etc.
* `src/hello/transforms/common/entities.py` is where you define your custom entities. Take a look at the examples provided if you want to play around with custom entities.
* `src/hello/resources` **FIXME**
* `src/hello/resources/etc` **FIXME**
* `src/hello/resources/etc/hello.conf` **FIXME**
* `src/hello/resources/external` directory is where you can place non-Python transforms written in other languages.
* `src/hello/resources/images` **FIXME**
* `src/hello/resources/maltego` directory is where your `entities.mtz` and `*.machine` files can be stored for auto install and uninstall.
```

---

**3. Your First Transform** - search for `$ canari create-profile hello` and... I would suggest to add before this line the following line `$ cd src/` just to be clear to new users

---

**4. Working With Input Entities** - search for `2. The parameters property returns a list of transform parameters.`
I dont understand which parameters property returns a list ... I look at (2) in code and dont understand ... =/

..and... (3) doesnt have a match on code...

---

**Comment by allfro** [comment]
Latest commit (3505c65cb5f5f135b2bd928c284396e5124ab066) adds note for `python-devel`
