### ISSUE TITLE
Do you intend to support Python 3?

### ISSUE THREAD

**Issue by RichardProsser** [redcanari/canari3#11]
I raised this as a question [in the forum](http://dev.paterva.com/developer/forum/viewtopic.php?pid=85#p85) but it did not get any replies, so I have decided to make this issue more formal, as I believe that it is important for the Maltego/Python community as a whole.

As I am sure you know, Python 2.7 or the like (that you currently use, I believe) does not offer consistent Unicode support, which is largely why the 3+ version was developed. Consequently I believe that your Python API should be ported to 3+ soon, as I expect that several of your customers will have interests in non-ASCII domains, so to speak.

I may be willing to do the porting myself (if my employers agree) but I have forgotten what the relevant GitHub process is exactly, so perhaps you could enlighten me on that point. FYI, I have more than three years' of Python development experience, 9 months with version 3.4/5. In addition I have worked as a software developer for 35+ years, mostly in the Unix/Linux arena.

Maltego looks very interesting but there is room for improvement IMO, especially where the Python code is concerned!

Richard
PS I would like to apply a "Question" label but I don't see how to do that.

**Comment by ndouba** [comment]
Python 3 with Python 2 backwards compat. would be great to have. We'd love your help on bringing the code up to snuff. Let us know what your thoughts are :)

**Comment by RichardProsser** [comment]
Thanks for the response. I am not sure about the backwards-compatibility aspects, I will have to think about that. What do we do about 'items' vs 'iteritems' for example? That may be OK in practice but I would need to check. Fortunately there isn't a lot of code and 2to3 can probably handle most of the grunt work.

Please advise on forking, branching or whatever would be required, plus testing of course.


Cheers,

Richard

**Comment by RichardProsser** [comment]
There are also "Type Annotations" to consider: I prefer the [comment-based version](http://mypy.readthedocs.io/en/latest/python2.html) myself and it is obviously useful for a backwards-compatible version of 3+ code.

This is something that could be done later however.

**Comment by RichardProsser** [comment]
I have run 'futurize --stage2 ...' against this code but the unit tests fail, due in part to this method (in config.py):

`class CanariConfigParser(SafeConfigParser):
    @staticmethod
    def _interpolate_environment_variables(value):
        if isinstance(value, str):
            value = string.Template(value).safe_substitute(os.environ)
        return value
`

In Python 3.5, 'value' is of type 'str' (as expected) but 'str' parameter itself is of type 'class NewStr', so the substitution never takes place.

[stackoverflow](http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility) suggest the usage of 'six'; making that change results in the corresponding test passing but there are still other faults to contend with.

As per my email today, I really would like some feedback from you as to how best to proceed. My own view is there should be separate API versions - the current one for legacy code, the new one for Python 3 (Unicode).

Richard

**Comment by allfro** [comment]
Hi Richard,

Please drop me a line on my personal email. Let's get a Skype call on the
go to go over what needs to be done. I'm not sure what the best approach
would be. My email is ndouba.at.gmail

**Comment by RichardProsser** [comment]
I sent an email to that address yesterday.

**Comment by allfro** [comment]
@RichardProsser sorry for not following up on this in a timely fashion, we have been swamped over here. I'd like to pick this back up with you if you are still interested in following up with this request?

**Comment by allfro** [comment]
There is a branch now for v3

**Comment by allfro** [comment]
v3.2.0 was just released with Python 3 support.
