### ISSUE TITLE
Unit test fails: <canari.unittests.test_resource.ResourceTests testMethod=test_image_resources>

### ISSUE THREAD

**Issue by RichardProsser** [redcanari/canari3#12]
I created an account at PythonAnywhere.com, for which 'uname -a' shows ...
Linux harry-liveconsole4 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I copied the code from your GitHub repository and ran the tests via `15:17 ~/canari3-master/src $ pytest canari`, with the following result:

`rootdir: /home/fs79/canari3-master, inifile: collected 83 items canari/unittests/test_config.py ..........................................canari/unittests/test_framework.py ....canari/unittests/test_mode.py .............canari/unittests/test_resource.py ...F>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>self = <canari.unittests.test_resource.ResourceTests testMethod=test_image_resources>    def test_image_resources(self):        images = image_resources('canari.unittests')        self.assertTrue(images)        self.assertTrue(len(images) == 4)        for i, j in enumerate(images):            print i,j>           self.assertTrue(j.endswith('canari/unittests/resources/images/%d.png' % i))E           AssertionError: False is not truecanari/unittests/test_resource.py:34: AssertionError`

Inspection via pdb revealed that the image files were not ordered in the manner expected by the test, hence the failure. Solution (I believe) is to change line #29 of test_resource.py as follows:
`images = sorted(image_resources('canari.unittests'))`. Test execution is successful then.

**Comment by allfro** [comment]
Awesome, thanks!

**Comment by allfro** [comment]
PR #20 should fix things
