### ISSUE TITLE
API does not appear to work on Windows!

### ISSUE THREAD

**Issue by RichardProsser** [redcanari/canari3#13]
> 18     def test_external_resource(self): 

> 19         resource = external_resource('wordlist.txt', 'canari.unittests.resources') 

> 20         self.assertTrue(resource.endswith('canari/unittests/resources/wordlist.txt')) 

> 21         self.assertTrue(os.path.lexists(resource))

I am running the unit tests (post-‘futurize’) on a Windows 7 machine and I get this kind of path for ‘resource’(line #19):

'C:\\Users\\Prosser_AD\\PycharmProjects\\Canari\\canari\\unittests\\resources\\wordlist.txt'

Naturally the test on line #20 fails; it seems that API was written without Windows users in mind – but I find that hard to believe.

This appears to be a fault in the original API or Unit Tests; I have not been able to successfully run the original tests as they stand (i.e. Python 2.7), though I have had to use unofficial versions of Python so far.

I could perhaps ‘fix’ the external_resource() function but I am not exactly sure what it is supposed to do, so I would appreciate your advice on this matter.

**Comment by allfro** [comment]
yes. I think this is a portability issue related to the `/` vs `\\` path separator. Changing line 20 to `resource.endswith(os.path.join(['canari', 'unittests', 'resources', 'wordlist.txt'])` may fix this issue

**Comment by allfro** [comment]
PR #20 should fix things
