### ISSUE TITLE
Author in generated MTZ is not propagated from package

### ISSUE THREAD

**Issue by wtfuzz** [redcanari/canari3#14]
After generating an mtz with `canari create-profile mypackage`, and importing into Maltego, all transforms are listed as being authored by Nadeem Douba.

**Comment by allfro** [comment]
Ouch. I'll take a look at it tonight. Don't know why that would be the case :(

**Comment by allfro** [comment]
Do you mind sending me a sample snippet of a transform file who's author info is being overwritten?

**Comment by wtfuzz** [comment]
Here's an example transform. Thanks for checking into it.

```from canari.maltego.entities import IPv4Address, Domain
from canari.maltego.transform import Transform
from canari.framework import EnableDebugWindow
from comox.client import Comox

__author__ = 'Hyas'
__copyright__ = 'Copyright 2017, comox Project'
__credits__ = []

__license__ = 'GPLv3'
__version__ = '0.1'
__maintainer__ = 'Hyas'
__email__ = 'matt@hyas.com'
__status__ = 'Development'


@EnableDebugWindow
class DomainPassiveHash(Transform):
    """Provides FQDN co-occurrence through malware sample network observations"""

    # The transform input entity type.
    input_type = Domain

    def do_transform(self, request, response, config):
        domain = request.entity
        client = Comox(config['comox.local.api_key'])
        res = client.domain_query(domain.value)

        limit = int(config['comox.local.limit'])
        for phash in sorted(res['passive_hash'], key=lambda x: x['count'], reverse=True):
            if(phash['domain'] != domain.value):
                response += Domain(fqdn=phash['domain'], weight=phash['count'])
                limit -= 1
                if(limit == 0):
                    break

        return response```

**Comment by wtfuzz** [comment]
To make sure I didn't have any instance of it in my package directory:

```
(canari3) Matts-MacBook-Pro:comox fuzz$ ls
MANIFEST.in	README		setup.py	src
(canari3) Matts-MacBook-Pro:comox fuzz$ find . -type f |xargs grep Nadeem
Binary file ./src/comox.mtz matches
```

**Comment by allfro** [comment]
Hmm.. Can you show me what's in your `__init__.py` file in the transforms package?

**Comment by wtfuzz** [comment]
```
(canari3) Matts-MacBook-Pro:comox fuzz$ cat transforms/__init__.py
__all__ = [
    'common'
]
```

**Comment by allfro** [comment]
The root `__init__.py` file under your `src` directory as well.

**Comment by wtfuzz** [comment]
```
(canari3) Matts-MacBook-Pro:comox fuzz$ ls -ls
total 24
8 -rw-r--r--  1 fuzz  staff   107 May 29 15:45 MANIFEST.in
8 -rw-r--r--  1 fuzz  staff  2371 May 29 15:47 README
8 -rwxr-xr-x  1 fuzz  staff   552 May 29 15:47 setup.py
0 drwxr-xr-x  6 fuzz  staff   204 May 29 17:16 src
(canari3) Matts-MacBook-Pro:comox fuzz$ cat src/comox/__init__.py
__all__ = [
    'transforms',
    'resources'
]
```

**Comment by allfro** [comment]
Here's a thought. Try defining `__author__` and `__email__`  in the root `__init__.py` file and see if it works.

**Comment by wtfuzz** [comment]
Unfortunately that didn't work. The generated .mtz still contains Nadeem, and no instances of Hyas.

**Comment by allfro** [comment]
Ok. I will file this as a bug and see if I can get a patch out soon for you. I'm not sure why my name is being propagated up to your transforms. Sorry about that ;) Hopefully I'm taking undeserved credit for an awesome project :D

**Comment by wtfuzz** [comment]
lol .. credit is deserved for your awesome project ;) really great python work!

One other thing, do you plan on adding support for Maltego built in Hash entities, or will I have to define custom entities to represent malware hashes?

**Comment by allfro** [comment]
Thank you :) 

Yes I certainly should update the builtin entities package to include everything in there. You can also do it yourself by using the `canari generate-entities` command while you're waiting for the update. It will automatically inspect the entities defined in an MTZ and create the equivalent Canari definitions. You would have to export the entities from Maltego as a first step of course.

**Comment by allfro** [comment]
Created an issue for this request #15

**Comment by wtfuzz** [comment]
Perfect! thanks a ton

**Comment by allfro** [comment]
Latest commit to master #17 should now fix this issue :)
