### ISSUE TITLE
Command: create-profile hello

### ISSUE THREAD

**Issue by SYNchroACK** [redcanari/canari3#2]
```
$ canari create-profile hello
...
$ ls -la 
canari.conf
hello/
hello.conf
hello.mtz
```

The following questions are related to "portability" issues... I mean, to a new user is not clear the `hello.mtz` dependencies from the canari.conf and hello.conf....
1. when `hello.mtz` is imported to maltego, it will use hello.conf file from this directory? What is best approach to have a hello.mtz "portable"?
2. `canari.conf` is used by `hello.mtz`?

**Comment by allfro** [comment]
Added a warning to the `create-profile` command documentation entries in #19
