### ISSUE TITLE
ImportError: cannot import name

### ISSUE THREAD

**Issue by pielco11** [redcanari/canari3#24]
Hi, so I'm trying to use some entities from Maltego. In particular I'm trying to use BtcAddress from PR package. I exported the entities and imported to canari, this is what I can see in `entities.py`

```python
 class BtcAddress(Entity):
   _category_ = 'Personal'
    _namespace_ = 'PR'
    properties_btcaddress = StringEntityField('properties.btcaddress', display_name='BtcAddress', is_value=True)
```

Now, how can I proceed? How can I use that entity ? I mean, something like `from canari.maltego.entities import BtcAddress` and so `response += BtcAddress(btc)`

**Comment by pielco11** [comment]
I solved defining the class in the transform itself, still looking for another solution

**Comment by allfro** [comment]
Hi there. Please add your entity to the `entities.py` file in your transform package. It's typically located under `yourpkgname/src/transforms/common/entities.py`. The import should be from `yourpkgname.transforms.common.entities`
