### ISSUE TITLE
Adding custom entities?

### ISSUE THREAD

**Issue by zmallen** [redcanari/canari3#27]
Hello, 

Does Canari support the ability to add an entity so it shows up in the entity panel of Maltego? I can create an entity and I see it rendered in transforms, but Im unsure how to import an entity from code into the pallet.

**Comment by allfro** [comment]
Hi Zack,

Custom entities can be developed and leveraged using the Canari framework.
I would highly recommend looking at the docs here:
http://canari3.readthedocs.io/en/latest/canari.maltego.message.html#using-and-defining-maltego-entities.
There is a full guide on using and defining maltego entities using Canari.
The general principle is that you have to design your entity in Maltego
first then use the “canari generate-entities” command within your project
folder to generate the custom entities.py file in your transform’s “common”
package. The documentation goes through a full end-to-end scenario using
the Canari Framework and it’s pretty brief. I would highly recommend going
through it once to see what you can leverage and how to structure your
project.

Hope this helps!

**Comment by zmallen** [comment]
Thank you! I didnt know I had to manually create entities and import them, I was seeing if I could create them via code and then import them to Maltego. This is very clear
