### ISSUE TITLE
Error while creating a basic transform

### ISSUE THREAD

**Issue by ZeeshanSultan** [redcanari/canari3#29]
Here take a look at this at let me know if any other information is required

![canari error](https://user-images.githubusercontent.com/8667667/33962179-798f7680-e072-11e7-8184-38279536ad24.jpg)

**Comment by FlankerZ** [comment]
run create-profile command in your-package\src path.

**Comment by allfro** [comment]
Hi @ZeeshanSultan 

The title and the screenshot don't seem unrelated. Profiles are maltego mtz files that get created for import once your transform package is complete. Creating a transform involves using the `canari create-transform` command. I am trying to replicate this issue with no luck. Mind sending me some repro steps?

Thanks!

**Comment by allfro** [comment]
Please feel free to reopen this issue if you are still running into it in v3.2.2
