### ISSUE TITLE
Maltego entities and corresponding fields

### ISSUE THREAD

**Issue by SYNchroACK** [redcanari/canari3#3]
In ```you have the following:

```
     l = Location()
        l.country = geoip_json.get('country_name', 'Unknown') # <--- 2
        l.city = geoip_json.get('city')
        l.countrycode = geoip_json.get('country_code')
        l.latitude = geoip_json.get('latitude')
        l.longitude = geoip_json.get('longitude')
        l.area = geoip_json.get('region_name')
```

How a new user can get a list of all entities and correspondent fields?
Should be provided by documentation in a table format or the new user should read `canari3/src/canari/maltego/entities.py` file? In case of read the `canari3/src/canari/maltego/entities.py` file, I think we should mention that in documentation.

**Comment by allfro** [comment]
Created the `generate-entities-doc` command to deal with this issue ;)
