### ISSUE TITLE
Can't debug transforms

### ISSUE THREAD

**Issue by tampe125** [redcanari/canari3#35]
Hello,

I just installed Canari and I'm trying to take a look around, however it seems I can't debug transforms:
```
$ debug-transform myproject.transforms.helloworld test

`- MaltegoTransformExceptionMessage:  
  `- Exceptions:  
    `- Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/maltego/runner.py", line 100, in local_transform_runner
    transform = load_object(transform)()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/maltego/runner.py", line 53, in load_object
    return module.__dict__[cls]
KeyError: 'helloworld'
```

I simply create the package using the built-in command, but it seems it doesn't find the class.  
If I use the transformation within Maltego it runs just fine.

**Comment by tampe125** [comment]
You can find it here: https://www.canariproject.com/4-3-transform-development-quick-start/

BTW that guide is outdated, where I can find the docs for the latest version?

**Comment by allfro** [comment]
Yes it is. You should look at
http://canari3.readthedocs.io/en/latest/canari.quickstart.html
