### ISSUE TITLE
Update the caller in local transform

### ISSUE THREAD

**Issue by tampe125** [redcanari/canari3#37]
I don't know if that's something doable, but it's possible to update the caller entity while running a local transform?
I tried to take a look at the code and the documentation, but I didn't find anything.

**Comment by allfro** [comment]
Hi Davide

I'm not sure what is meant by updating the caller entity? Could you please
elaborate?

**Comment by tampe125** [comment]
Yeah, sorry.
Let's say that I want to run a transform that will update a property of the current entity, instead of producing a new entity that will be added to the graph.
Is that possible? I simply have to return the request object in the response?

**Comment by tampe125** [comment]
Sorry to bother you again, but when I try to do that I got the following error from Maltego:

> Could not resolve message type returned by transform

By the way, what I was trying to do is to create new entities back to the graph _and_ update the current entity.

**Comment by allfro** [comment]
Could you post a code snippet and the stack trace by any chance? Also add
the Debug annotation to your transform class.

**Comment by tampe125** [comment]
You can easily try with the HelloWorld transform.  

First case: return the requested entity along with other new entities results in a new one.
![new_entitty](https://user-images.githubusercontent.com/606707/39965449-fe4b0f32-5698-11e8-9e08-571ff8d0da82.png)

Code
```
@EnableDebugWindow
class HelloWorld(Transform):
    input_type = Person

    def do_transform(self, request, response, config):
        person = request.entity
        response += Phrase('Hello %s!' % person.value)
        response += Phrase('This way Mr(s). %s!' % person.lastname)
        response += Phrase('Hi %s!' % person.firstnames)

        person.firstnames = "test"

        response += person

        return response
```

Debug output:
```
<MaltegoMessage><MaltegoTransformResponseMessage><UIMessages /><Entities><Entity Type="maltego.Phrase"><Value>Hello John Doe!</Value><Weight>1</Weight></Entity><Entity Type="maltego.Phrase"><Value>This way Mr(s). Doe!</Value><Weight>1</Weight></Entity><Entity Type="maltego.Phrase"><Value>Hi John!</Value><Weight>1</Weight></Entity><Entity Type="maltego.Person"><AdditionalFields><Field Name="lastname" MatchingRule="strict">Doe</Field><Field Name="person.fullname" MatchingRule="strict">John Doe</Field><Field Name="firstname" MatchingRule="strict">test</Field></AdditionalFields><Value>John Doe</Value><Weight>1</Weight></Entity></Entities></MaltegoTransformResponseMessage></MaltegoMessage>
``` 

Returning the same request entity in the response, results in a Maltego error:
![error](https://user-images.githubusercontent.com/606707/39965465-5cd5b034-5699-11e8-9028-4bb1a10f2269.png)

Code:
```
@EnableDebugWindow
class HelloWorld(Transform):

    input_type = Person

    def do_transform(self, request, response, config):
        person = request.entity
        person.firstnames = "test"
        
        return person
```

Debug output:
```
<MaltegoMessage><MaltegoTransformExceptionMessage><Exceptions><Exception>Could not resolve message type returned by transform.</Exception></Exceptions></MaltegoTransformExceptionMessage></MaltegoMessage>

```

**Comment by allfro** [comment]
You need to return response. So `return response + person` should work

**Comment by tampe125** [comment]
I'm sorry, that works but creates a new entity, it doesn't update the original one

**Comment by allfro** [comment]
Sorry for the delay in responding. What you are experiencing is expected
behaviour. Take a look at this section:
http://canari3.readthedocs.io/en/latest/canari.maltego.message.html#matching-rules.
You probably need to loose match properties in entities. The built in
entities all have strict matching properties. The documentation goes into
the explanation of how this works.

**Comment by tampe125** [comment]
Ok, thank you very much for the info.
You can close this ticket since the original issue has been resolved.
