### ISSUE TITLE
creating multiple hierarchical entities in a Transform

### ISSUE THREAD

**Issue by cvandeplas** [redcanari/canari3#39]
I'm currently following the documentation working on my first transform.
The special thing is that my transform should create two (or maybe more) layers of entities in the result as some of the expanded entries need to be grouped together. (the group is a custom Maltego Entity)

I know the normal Maltego recommendation is not to do this, as the user should decide himself how deep he wants to go. However my use-case is only because some of my new entities need to be grouped together logically. 

Is there a way to do this with canari? Thanks ! 

Example: 
```
 ------------------
 | OriginalEntity | -- new link -- NewEntity 1
 ------------------ -- new link -- NewEntity 2
    |  |
    | new link
    |  |
    |  |   --------------------
    |  ----| NewEntityGroup 1 | -- new link -- NewEntity 3
    |      -------------------- -- new link -- NewEntity 4
  new link
    |   --------------------
    ----| NewEntityGroup 2 | -- new link -- NewEntity 5
        -------------------- -- new link -- NewEntity 6
```

**Comment by allfro** [comment]
I'm not sure I understand the question.  You want to output a graph instead of just child entities? If this is the case, Maltego doesn't support graph out yet.

**Comment by allfro** [comment]
Unfortunately, that’s not possible for Maltego. The closest thing you can do is script a bunch of transforms together using the Maltego machines API.

**Comment by cvandeplas** [comment]
too bad, thanks for the feedback ! I'll try to read about the machines API, but I fear it might become too complex.
