### ISSUE TITLE
Creating an input link to a parent entity

### ISSUE THREAD

**Issue by mshirley** [redcanari/canari3#42]
By default, appending entities to a response object creates a graph relationship with an output from the parent to the children entities.

How do i go about creating a new parent to an existing parent object entity rather than creating a child entity?  In other words, how do I create an arrow going from a child object back to the parent rather than an arrow pointing from the parent to the children?

**Comment by jakub** [comment]
I don't believe Canari can currently do this. I don't know enough Python to know how to write the proper tests for this package yet, but the change needed is easy enough: https://github.com/jakub/canari3/commit/6cba2166b5c2833b8751049c93bf0927c3ff7cd5

**Comment by allfro** [comment]
Neat. We didn’t know this was possible. The code changes look good. Send a
PR pls ;)

**Comment by mshirley** [comment]
I hope @jakub  doesn't mind.  I created a pr.

https://github.com/redcanari/canari3/pull/43

**Comment by jakub** [comment]
Sounds good to me 👍

**Comment by allfro** [comment]
We're just about to commit this enhancement. Thanks for your contributions.

**Comment by allfro** [comment]
Fixed here: 503a763944ee2bdc7c7db6339ad3cdb4fd11de5a. Thanks!
