### ISSUE TITLE
Entity property, if used as Entity.value, displays as 'Temp'

### ISSUE THREAD

**Issue by maxlandon** [redcanari/canari3#55]
When an Entity property (defined in its class) is used as the Entity's value, the display_name of this properties becomes 'Temp'.

(This is not a huge problem because it does not interfere with getting/setting the property in the Python code.)

**Comment by allfro** [comment]
This is probably because you don't have the entity defined in the Maltego GUI first or the namespace + entity name do not match what's defined in the GUI.
