### ISSUE TITLE
Various questions around _namespace_, _type_ and _alias_

### ISSUE THREAD

**Issue by maxlandon** [redcanari/canari3#56]
#### I - Interest of namespace in getting/setting properties.
Entity classes have `_namespace_`, `_type_`, and `_alias_` attributes. At least concerning namespace and type, they seem to be useful only to the Maltego client's logic. 
(This conclusion is based on the fact that these namespaces are not called in Python as `threat.ip.location`: they can only be used in dictionary indexing methods `dict['threat.ip.location'])`.

*1) Is my description right ?*
*2) If yes, do you -personally- make use of namespace, type and alias attributes?*

#### II - Using _type_, _namespace_ and _alias_ properties.
Let's consider the following Entity class.
```python
class MetasploitHost(Entity):
	_namespace_ = 'EffectiveCouscous.metasploit.host'
	_category_ = 'Penetration Testing'
	_alias_ = 'Metasploit Host'
```

This Entity, when spawned in Maltego, will exhibit `EffectiveCouscous.metasploit.host.MetasploitHost` in the Detail view.
This name will also be displayed in the "on-graph-list" of entities (at bottom) and in the "Search by Type" button.

*1) I can't see the interest of having an `_alias_` property here. Do you have any explanations ?*

Now let's consider.
```python
class MetasploitHost(Entity):
	_namespace_ = 'EffectiveCouscous.metasploit.host'
	_category_ = 'Penetration Testing'
	_type_ = 'Metasploit Host'
```

Given this class, the _namespace_ seems to be completely overwritten in the Maltego client, and the Detail view will show [Metasploit Host]

*1) Do I need to conclude that using _type_ and _namespace_ at the same time is not a good idea ? 
	( I have read the doc about this, please excuse me but it was not clear to me...)*
*2) Do you have any tips/advices concerning this ?*

**Comment by allfro** [comment]
The `_namespace_`, `_category_`, and `_alias_` properties are only useful to the Maltego client. `_alias_` is a legacy property to address some anomalies in the Maltego client. You should never use that property unless you are tweaking the  Maltego builtin entity types in Canari. `_type_`, if set, should define the `namespace.EntityName` of the entity. This is also another property that should rarely be used unless you really want to use it. Canari uses the following convention for determining an entity's namespace and name: 

* The `_namespace_` is set to the package name unless explicitly defined. If your transform package is `foo` then the `_namespace_` will be `foo`
* The `_type_` is set to `cls._namespace_` + `cls.__name__`. So if your entity class name is 'FooEntity' and your package is `foo`, the entity's fully qualified name will be `foo.FooEntity`. 

The final result of `_type_` should match what is in your GUI. You can use `canari generate-entities` on a custom export of your entities from Maltego to get Canari to generate your entity definitions.

**Comment by maxlandon** [comment]
Hello @allfro !
Let me thank you for the questions in the other threads, as a one-shot.
THANKS A ZILLION TIMES !
Wishing you good luck and fun in projects, as much as I have using Canari !
