### ISSUE TITLE
SSL Certificate Entity

### ISSUE THREAD

**Issue by thehappydinoa** [redcanari/canari3#69]
Hi,

I was wondering if the SSL Certificate (`maltego.X509Certificate`) was going to be added to the common entity definitions.

**Comment by allfro** [comment]
It used to be but it probably isn't anymore. I think this is something from the legacy version of Maltego

**Comment by thehappydinoa** [comment]
Ah okay, I am just using `Hash` and adding `type="maltego.X509Certificate"`. Thanks for the fast reply!

**Comment by allfro** [comment]
I think I misunderstood the question. I thought you were asking if Maltego was ever going to add that entity. You can just inherit the `Entity` type and create your own entities if you like. It's not fixed to whatever is in the `common` package. A pull request is welcome as well.

**Comment by thehappydinoa** [comment]
Ah sorry, Maltego has an SSL Cert entity that comes with community addition. Its in the same section as Hash in common_definitions.
